"""SQLAlchemy ORM models."""
from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Integer, String, Text, JSON, Index,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from ..core.database import Base


def _now():
    return datetime.now(timezone.utc)


class User(Base):
    __tablename__ = "users"

    id           = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    email        = Column(String(255), unique=True, nullable=False, index=True)
    hashed_password = Column(String(255), nullable=False)
    name         = Column(String(255))
    is_active    = Column(Boolean, default=True)
    created_at   = Column(DateTime(timezone=True), default=_now)

    projects     = relationship("Project", back_populates="owner")


class Project(Base):
    __tablename__ = "projects"

    id              = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name            = Column(String(255), nullable=False)
    api_key         = Column(String(128), unique=True, index=True, default=lambda: str(uuid.uuid4()))
    owner_id        = Column(UUID(as_uuid=True), ForeignKey("users.id"), nullable=False)
    created_at      = Column(DateTime(timezone=True), default=_now)
    # Controls how aggressively the heuristic agent fires suggestions:
    #   "instant"      — fires after minimal data (1+ calls, very low cost thresholds)
    #   "balanced"     — requires ~7 days of data and moderate spend (default)
    #   "conservative" — requires 30 days and significant spend before suggesting
    suggestion_mode = Column(String(32), nullable=False, default="balanced", server_default="balanced")

    owner        = relationship("User", back_populates="projects")
    events       = relationship("LLMEvent", back_populates="project")
    suggestions  = relationship("Suggestion", back_populates="project")


class LLMEvent(Base):
    """Raw telemetry event from the SDK."""
    __tablename__ = "llm_events"
    __table_args__ = (
        Index("ix_llm_events_project_ts", "project_id", "timestamp"),
        Index("ix_llm_events_feature_tag", "feature_tag"),
    )

    id               = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    event_id         = Column(String(64), unique=True, index=True)  # client-generated
    project_id       = Column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)

    timestamp        = Column(DateTime(timezone=True), nullable=False)
    latency_ms       = Column(Float)

    provider         = Column(String(64))
    model            = Column(String(128))
    endpoint         = Column(String(128))

    input_tokens     = Column(Integer, default=0)
    output_tokens    = Column(Integer, default=0)
    total_tokens     = Column(Integer, default=0)
    estimated_cost   = Column(Float, default=0.0)   # USD

    feature_tag      = Column(String(128), index=True)
    user_id          = Column(String(64))
    session_id       = Column(String(64))

    rag_chunks       = Column(Integer, default=0)
    error            = Column(String(256))
    status_code      = Column(Integer)

    ingested_at      = Column(DateTime(timezone=True), default=_now)
    project          = relationship("Project", back_populates="events")


class Suggestion(Base):
    """An optimization suggestion generated by an agent."""
    __tablename__ = "suggestions"

    id             = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id     = Column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)
    created_at     = Column(DateTime(timezone=True), default=_now)

    suggestion_type = Column(String(64))   # model_downgrade, prompt_compress, routing, ...
    feature_tag    = Column(String(128))
    title          = Column(String(255))
    description    = Column(Text)

    # Evidence
    current_cost_per_day  = Column(Float)
    projected_cost_per_day = Column(Float)
    estimated_savings_pct = Column(Float)
    accuracy_risk         = Column(String(32))   # low, medium, high
    confidence            = Column(Float)         # 0-1

    # Payload: model to use, compressed prompt snippet, routing rule, etc.
    payload        = Column(JSON)

    status         = Column(String(32), default="pending")  # pending, simulated, applied, dismissed
    applied_at     = Column(DateTime(timezone=True))

    project        = relationship("Project", back_populates="suggestions")


class DailyMetric(Base):
    """Pre-aggregated daily rollups per project + feature_tag."""
    __tablename__ = "daily_metrics"
    __table_args__ = (
        Index("ix_daily_metrics_project_date", "project_id", "date"),
    )

    id             = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    project_id     = Column(UUID(as_uuid=True), ForeignKey("projects.id"), nullable=False)
    date           = Column(String(10), nullable=False)   # YYYY-MM-DD
    feature_tag    = Column(String(128), default="__all__")

    total_calls    = Column(Integer, default=0)
    total_tokens   = Column(Integer, default=0)
    total_cost     = Column(Float, default=0.0)
    avg_latency_ms = Column(Float, default=0.0)
    error_count    = Column(Integer, default=0)

    # Model breakdown (JSON: {model: count})
    model_breakdown = Column(JSON, default=dict)
